title:             NYCycles
email:             citibikexstuy@gmail.com
description:       Updates about CitiBike, livable streets, and NYC
author:            NYCycles
baseurl:           ""
url:               "http://jhuang20.github.io"

# Social Profiles
twitter_username:  stuycommutes
github_username:   jhuang20
facebook_username: stuycommutes

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
