title:             CitiBike X Stuy Updates
email:             citibikexstuy@gmail.com
description:       Keeping you updated on CitiBike!
author:            James Huang
baseurl:           ""
url:               "http://blog.stuybikes.com"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
